version: "3.7"
services:

  php:
    image: php:7.4-fpm
    volumes:
        - ./src:/var/www
    working_dir: /var/www
    depends_on:
     - mysql
    networks:
      php:
      mysql:
    stdin_open: true
    tty: true

  # Database
  mysql:
    image: mariadb
    networks:
      mysql:
    ports:
      - 127.0.0.1:13306:3306
    # OPTIONAL: Mount the data as volume for persistence
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: secret

volumes:
  mysql:

networks:
  php:
  mysql:
